# Generated by Django 5.0.6 on 2025-06-27 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participacion',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participacion',
            name='tiempo_total',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='tiempo_limite',
            field=models.IntegerField(default=0, help_text='Tiempo en minutos (0 = sin límite)'),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='participacion',
            unique_together={('usuario', 'quiz')},
        ),
    ]
